{% set name = "fides" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fides-{{ version }}.tar.gz
  sha256: bde89c10c4a346f5a5b9dd6994f8e5f11ec871f9725fcf0efabfeb0c56ad9c94

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=52.0.0
    - wheel >=0.36.2
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.19.2
    - scipy >=1.5.2
    - h5py >=3.5.0

test:
  imports:
    - fides
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/fides-dev/fides
  summary: python-based Trust Region Optimization toolbox
  license: BSD-3-Clause
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - renan-r-santos
